### PR TITLE
Support for stacking modals

### PR DESCRIPTION
**Pull request by antstorm**
**Do not merge this yet!**

Ok, this is not something I really like, but some people think that stacking modals is not that bad. One of those people being the designer in the company I work for :)

I really like Remodal and wanna continue using it, but for this I need stacking modals on top of each other. I've made some initial changes to the library in order to support that.

Basically changes include:

- Overlay `div` is moved inside the `wrapper`, so that every modal has it's own overlay
- Instead of a global `remodal-is-active` class, I'm using `remodal-is-opened` class on a `wrapper`, that allows showing/hiding individual modals
- There's a `stack` option in settings that determines wether the modal should replace the current one of stack on top of it. Default is `false` in order to keep original behaviour

So I know that it kinda goes against your original idea, but this is quite a minimal change that won't fight people trying to implement this behaviour.

This is still work in progress, just wanted to make sure you are happy with the direction this is going. Otherwise I'll have to maintain a version of Remodal, that supports stacking, which is something I'm not sure I wanna do (keeping two versions of the same library).

In case you're happy to proceed I'll do some refactoring, add usage examples and update docs.

### CODE REVIEW

**Comment by AlecRust** [comment]
Fantastic! Really needed this imo. :+1:

**Comment by VodkaBears** [comment]
:+1:

**Comment by kohaistyle** [comment]
Truly needed ! Stackable modals for confirm/yes-no windows, for exmaple

**Comment by VodkaBears** [comment]
I develop the new version - 1.0.0(in the 'dev' branch). So, i don't accept any PR until v1.0.0 will be released. Sorry.

**Comment by VodkaBears** [comment]
With API of the v1.0.0 it will be possibe to make this in minor versions without incompabilities.

**Comment by PoeHaH** [comment]
Shouldn't there be a line of code that enlarges the z-Index on the wrapper? How can this work with always the same z-index?

**Comment by antstorm** [comment]
@PoeHaH correct me if I'm wrong, but elements with the same `z-index` stack on top each other, latest to appear in HTML to be on the top.

**Comment by antstorm** [comment]
@VodkaBears since the 1.0.0 is out, I'm gonna resurrect this PR. Or maybe open another one, since this one's not gonna merge very well.

**Comment by VodkaBears** [comment]
Cool. Create another one, pls, i'll close it.

**Comment by PoeHaH** [comment]
@antstorm i also thought that, but it wasn't working for me so I added incremental zIndex, which fixed my issues.

**Comment by antstorm** [comment]
@PoeHaH good to know that! I'll definitely take this into account.

**Comment by whwnow** [comment]
it has released 1.0.1 now . waiting this ! @antstorm

**Comment by antstorm** [comment]
Here's the new PR — #162. Let's get done and it merged.

**Pull request closed without merging**
