### PR TITLE
Stacking modals

### PR DESCRIPTION
**Pull request by antstorm**
Hi all,

This is initial work on the support for stacking modals. Because it involves some major changes and reconsiderations I've decided to put it out earlier so that we can all agree on how it should be done properly. This is by no means a complete implementation, so keep that in mind.

The good news is that it works and can be tested be opening `examples/index.html`.

Any comments/feedback/reviews are very welcome.

Meanwhile I'm working on the hash tracking support for stacking modals.

### CODE REVIEW

**Comment by pavsid** [comment]
Hi @antstorm thanks for this, works great except that the z-indexing is getting a bit messed up on my implementation when you close all modals and then re-open them again.

I think the reason is that the stacked modal as an alert box, which is dynamically created when called, and so it is getting re-created each time. Each time the inital modal is created, the z-index values increment, but the alert box z-index remains the same and so starts appearing behind the newly created initial modal.

I can easily fix it on my installation by giving a much higher z-index on the alert boxes in the CSS, but that probably won't work for others with more stacked modals.

**Comment by antstorm** [comment]
@pavsid thanks for trying this out. I'll fix the z-index issue

**Comment by KoesterD** [comment]
Great idea! Anyone still working on this?

**Comment by pavsid** [comment]
@antstorm Is this any closer to being merged into the production branch? Could do with this in v1.0.5

**Comment by antstorm** [comment]
@pavsid sorry mate, I was busy with my day job. Will pick this up

**Comment by pavsid** [comment]
@antstorm No worries man, it was more directed at @VodkaBears to see if it was going to be considered for inclusion. Thanks for your work, has really helped!

**Comment by kouts** [comment]
Stackable modals would be a great feature, +1 from me.

**Pull request closed without merging**
